name: Daily Digest Email

on:
  schedule:
    # Runs at 08:00 UTC (9:00 AM CET) every day
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: Managerial Economics Daily Digest - New Update
          to: peetxeberria@faculty.ie.edu
          from: Managerial Economics Digest <${{ secrets.GMAIL_USERNAME }}>
          content_type: text/html
          body: |
            <!DOCTYPE html>
            <html>
            <body>
              <p>Hello,</p>
              <p>The <strong>Managerial Economics Daily Digest</strong> has been updated with today's news.</p>
              <p>You can access the digest here: <a href="https://danielfernandezkranz-cmyk.github.io/Managerial-Economics-Daily-Digest/">Managerial Economics Daily Digest</a></p>
              <br>
              <p>Best regards,</p>
              <p>Prof. Daniel Fernández Kranz</p>
            </body>
            </html>
